version: '3'

services:
  mongodb:
    container_name: mulocdeepdb
    image: mongo:4.2.1
    restart: always
    command: mongod --port 65521
    ports:
      - "65521:65521"
    volumes:
      - ~/data/db:/data/db
    networks:
      - webapp-network
  web:
    build: .
    container_name: mulocdeepweb
    image: mulocdeep/mulocdeepweb
    restart: always
    ports:
      - '8082:8082'
    depends_on:
      - mongodb
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge